INSERT INTO MythicHeroes_Factions
    ( name, imageUrl, imageSourceUrl )
VALUES
    ( 'Luminarch & Shadowarch', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/7/7a/LuminarchShadowarch.png/revision/latest?cb=20211112165529' ),
    ( 'Luminarch & Verdian', '', '' ),
    ( 'Luminarch & Guardian', '', '' ),
    ( 'Shadowarch & Verdian', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/e/ec/ShadowarchVerdian.png/revision/latest?cb=20211229163412' ),
    ( 'Shadowarch & Guardian', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/b/b6/ShadowarchGuardian.png/revision/latest?cb=20211204184241' ),
    ( 'Guardian & Verdian', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/f/ff/GuardianVerdian.png/revision/latest?cb=20211205162654' ),
    ( 'Luminarch', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/a/a2/Luminarch.png/revision/latest?cb=20210728223148' ),
    ( 'Shadowarch', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/8/8d/Shadowarch.png/revision/latest?cb=20210728223058' ),
    ( 'Guardian', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/f/fd/Guardian.png/revision/latest?cb=20210728223230' ),
    ( 'Verdian', '',
      'https://static.wikia.nocookie.net/mythic-heroes/images/7/71/Verdian.png/revision/latest?cb=20210728223318' );

INSERT INTO MythicHeroes_Rarities
    ( name, imageUrl, imageSourceUrl )
VALUES
    ( 'UR', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/09/Rarity_Ur-1.png' ),
    ( 'SSR', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/Rarity_Ssr.png' ),
    ( 'SR', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/Rarity_Sr.png' );

INSERT INTO MythicHeroes_Types
    ( name, imageUrl, imageSourceUrl )
VALUES
    ( 'Tank', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Tank.png' ),
    ( 'Fighter', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Damage.png' ),
    ( 'Mage', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Mage.png' ),
    ( 'Support', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Support.png' );

INSERT INTO MythicHeroes_Artifacts
    ( name )
VALUES
    ( 'Axe of Pangu' ),
    ( 'Staff of Sharur' ),
    ( 'Sudarshana Chakra' ),
    ( 'Yasakani Magatama' ),
    ( 'Excalibur' ),
    ( 'Thor''s Hammer' ),
    ( 'Scarab Badge' ),
    ( 'Aegis Shield' );

INSERT INTO MythicHeroes_Runes
    ( name )
VALUES
    ( 'Earth' ),
    ( 'Water' ),
    ( 'Fire' ),
    ( 'Air' ),
    ( 'Thunder' ),
    ( 'Forest' ),
    ( 'Light' ),
    ( 'Dark' );

INSERT INTO MythicHeroes_Heroes
    ( name, imageUrl, imageSourceUrl, factionId, rarityId, typeId )
VALUES
--UR
--Luminarch & Shadowarch
( 'Lucifer', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-5-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch & Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
--Luminarch & Verdian
( 'Iset', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/smallportrait-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch & Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
--Luminarch & Guardian
( 'Amaterasu', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/03/website_icon-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch & Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
--Shadowarch & Verdian
( 'Typhon', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/12/small-portrait-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch & Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
--Shadowarch & Guardian
( 'Lilith', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/tinyprofile-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch & Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
--Guardian & Verdian
( 'Nuwa', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-23-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian & Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'UR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
--SSR
--Luminarch
( 'Zeus', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-8-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Athena', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-1-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Susanoo', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-7-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Artemis', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Dionysus', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-3-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Thor', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/11/tinyprofile-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Western Queen', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/02/tinyprofile-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Odin', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/04/website_icon-1-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
--Shadowarch
( 'Persephone', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyportrait-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Izanami', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-13-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Hades', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-11-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Medusa', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-14-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Anubis', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-9-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Hela', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/12/Smallportrait-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Faust', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/02/tinyprofile-1-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Loki', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/04/website_icon-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
--Guardian
( 'Hercules', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-18-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Lu Bu', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-21-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Ganjiang & Moye', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-17-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Joan of Arc', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-20-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Cleopatra', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-16-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Cassandra', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-16-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Archimedes', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-16-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Leonidas', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-16-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
--Verdian
( 'Nagakayna', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-28-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Tamamo no Mae', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-30-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Idun', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-27-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Gaia', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-25-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Oberon', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-29-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Flora', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/tinyprofile-2-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Poseidon', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/01/tinyprofile-1-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Freyja', '', 'https://www.mythicheroes.com/wp-content/uploads/2022/05/website_icon-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SSR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
--SR
--Luminarch
( 'Baldur', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-2-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Muse', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/09/smallportrait-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
( 'Eos', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-4-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Luminarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
--Shadowarch
( 'Thanatos', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-15-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Hodur', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-12-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Dracula', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-10-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Shadowarch'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
--Guardian
( 'Hippolyta', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-19-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Mulan', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-32-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Fighter') ),
( 'Merlin', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-22-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Guardian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') ),
--Verdian
( 'Yukionna', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-31-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Mage') ),
( 'Ganesha', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-24-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Tank') ),
( 'Harpy', '', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-26-120x120.png',
  (SELECT id FROM MythicHeroes_Factions WHERE name = 'Verdian'),
  (SELECT id FROM MythicHeroes_Rarities WHERE name = 'SR'),
  (SELECT id FROM MythicHeroes_Types WHERE name = 'Support') );
