INSERT INTO MythicHeroes_Factions
    (FactionName, FactionImageUrl)
VALUES
    ('Luminarch', 'https://www.game.guide/wp-content/uploads/2021/09/Luminarch_Icon.png'),
    ('Shadowarch', 'https://www.game.guide/wp-content/uploads/2021/09/Shadowarch_Icon.png'),
    ('Guardian', 'https://www.game.guide/wp-content/uploads/2021/09/Guardian_Icon.png'),
    ('Verdian', 'https://www.game.guide/wp-content/uploads/2021/09/Verdian_Icon.png'),
    ('Luminarch & Shadowarch', 'https://www.game.guide/wp-content/uploads/2021/09/Luminarch_Shadowarch_Icon.png'),
    ('Shadowarch & Guardian', 'https://www.game.guide/wp-content/uploads/2021/10/Shadowarch_Guardian_Icon-150x150.png'),
    ('Guardian & Verdian', 'https://www.game.guide/wp-content/uploads/2021/09/Verdian_Guardian_Icon.png'),
    ('Luminarch & Verdian', '');

INSERT INTO MythicHeroes_Rarities
    (RarityName, RarityImageUrl)
VALUES
    ('UR', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/Rarity_Ur.png'),
    ('SSR' , 'https://www.mythicheroes.com/wp-content/uploads/2021/08/Rarity_Ssr.png'),
    ('SR', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/Rarity_Sr.png');

INSERT INTO MythicHeroes_Types
    (TypeName, TypeImageUrl)
VALUES
    ('Tank', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Tank.png'),
    ('Fighter', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Damage.png'),
    ('Mage', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Mage.png'),
    ('Support', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/HeroFilters_Button_Class_Support.png');

INSERT INTO MythicHeroes_Heroes
    (HeroName, HeroImageUrl, FactionId, RarityId, TypeId)
VALUES
--UR
--Luminarch & Shadowarch
    ('Lucifer', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-5-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch & Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='UR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
--Luminarch & Verdian
    ('Iset', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/smallportrait-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch & Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='UR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
--Shadowarch & Guardian
    ('Lilith', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/tinyprofile-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch & Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='UR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
--Guardian & Verdian
    ('Nuwa', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-23-120x120.png',
            (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian & Verdian'),
            (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='UR'),
            (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
--SSR
--Luminarch
    ('Zeus', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-8-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Athena', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-1-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Susanoo', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-7-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Artemis', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Dionysus', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-3-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
--Shadowarch
    ('Persephone', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyportrait-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Izanami', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-13-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Hades', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-11-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Medusa', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-14-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Anubis', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-9-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
--Guardian
    ('Hercules', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-18-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Lu Bu', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-21-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Ganjiang & Moye', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-17-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Joan of Arc', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-20-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
    ('Cleopatra', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-16-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
--Verdian
    ('Flora', 'https://www.mythicheroes.com/wp-content/uploads/2021/10/tinyprofile-2-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Nagakayna', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-28-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
    ('Tamamo no Mae', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-30-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Idun', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-27-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
    ('Gaia', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-25-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Oberon', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-29-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SSR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
--SR
--Luminarch
    ('Baldur', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-2-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Muse', 'https://www.mythicheroes.com/wp-content/uploads/2021/09/smallportrait-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
    ('Eos', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-4-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Luminarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
--Shadowarch
    ('Thanatos', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-15-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Hodur', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-12-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Dracula', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-10-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Shadowarch'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
--Guardian
    ('Hippolyta', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-19-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Mulan', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-32-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Fighter')),
    ('Merlin', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-22-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Guardian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support')),
--Verdian
    ('Yukionna', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-31-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Mage')),
    ('Ganesha', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-24-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Tank')),
    ('Harpy', 'https://www.mythicheroes.com/wp-content/uploads/2021/08/tinyprofile-26-120x120.png',
        (SELECT FactionId from MythicHeroes_Factions WHERE FactionName='Verdian'),
        (SELECT RarityId from MythicHeroes_Rarities WHERE RarityName='SR'),
        (SELECT TypeId from MythicHeroes_Types WHERE TypeName='Support'));
